name: flutter_adaptive_button
description: "A Flutter package that provides a custom button that adapts to the platform's design guidelines."
version: 0.0.1
repository: https://github.com/YoussefLasheen/flutter_adaptive_button
issue_tracker: https://github.com/YoussefLasheen/flutter_adaptive_button/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
